general = {disable_mod = false, hide_bossbar = true, shadow_text = true, auto_start = false, hide_debug_crosshair = false, background_color = 1867534416, space_modules = true, animations = false, fontScale = 1.0, hide_sidebar = true}

[[modules_right]]
name = "system"
name_color = 13421772
value_color = 10066329
lines = {opengl_version = true, java_version = true, memory_usage = true, allocated_memory = true, cpu = true, gpu = true, gpu_utilization = true, time = true, tps = true}
enabled = true
empty_lines = 1

[[modules_right]]
name = "network"
name_color = 13421772
value_color = 10066329
lines = {ping = true}
enabled = true
empty_lines = 2

[[modules_right]]
name = "target"
name_color = 10079487
value_color = 16777215
lines = {targeted_block = true, targeted_entity = true}
enabled = true
empty_lines = 2

[[modules_left]]
name = "fps"
color_high = 12040119
color_med = 14474460
color_low = 15658496
lines = {fps = true}
enabled = true
empty_lines = 1

[[modules_left]]
name = "coords"
name_color = 13421772
color_x = 15658496
color_y = 14474460
color_z = 12040119
lines = {player_coords = true, block_coords = true, biome = true, dimension = true, day_time = true}
enabled = true
empty_lines = 2
